### ISSUE TITLE
ppa:graysky/utils has no profile-sync-daemon for trusty

### ISSUE THREAD

**Issue by RiaanBurger** [graysky2/profile-sync-daemon#123]
I'm trying an RC of Mint 17.2, it's should be out in a day or two. Mint 17-series is built on Ubuntu 14.04 LTS (trusty).

When I try to install using ppa:graysky/utils there is no package candidate to install.

I checked https://launchpad.net/~graysky/+archive/ubuntu/utils

When the filter is set to trusty, the profile-sync-daemon package disappears:

https://launchpad.net/~graysky/+archive/ubuntu/utils?field.series_filter=trusty

Does this mean Mint 17.2 (or even any distro based on Ubuntu 14.04 LTS) is no longer supported/available?

**Comment by graysky2** [comment]
No, it is supported, but I do not provide a compiled package.  This is due to Ubuntu/Debian switching to systemd by default.  Keeping their packaging scripts smart enough to know which version needs upstart and which needs systemd init files it too much overhead for me, so I have chosen to only build the packages for systemd to keep it simple.

You can build it yourself very easily, just remember to enable it in your init system (upstart):
As root or via sudo:
```
update-rc.d -f psd remove
update-rc.d psd defaults
```

**Comment by RiaanBurger** [comment]
Thank you graysky2! That worked like a charm.
