### ISSUE TITLE
Don't use a hidden file in ~/.config/psd

### ISSUE THREAD

**Issue by trizen** [graysky2/profile-sync-daemon#151]
Hello Graysky,

Just a minor issue here: it seems like `psd` uses a hidden config file ( `.psd.conf` -- https://github.com/graysky2/profile-sync-daemon/blob/master/common/profile-sync-daemon.in#L66) instead of `psd.conf`.

I just discovered that I have two files in `~/.config/psd`. I'm not sure if this is intended, as it conflicts with the documentation and may cause some confusion.

Hope it will get fixed. Nice tool, btw. Keep up the good work!

**Comment by graysky2** [comment]
Yes, it is by design.  The hidden copy is created when psd is active and thus keeps your data sane.  Without it, if you were to edit psd.conf, each time the script is run, it would source it which could lead to bad things particularly if browsers are changed while active.  I had this more prominently featured in the manpage in the past but wanted a less complicated version more recently.

**Comment by trizen** [comment]
Oh, got it. Thanks
