### ISSUE TITLE
Bug when profile directory contains spaces

### ISSUE THREAD

**Issue by arshesney** [graysky2/profile-sync-daemon#213]
I'm using Profile-sync-daemon v6.31 on Arch Linux x64, 
trying to sync two Firefox profiles:

```
xxxxxxxx.Default User
yyyyyyyy.Default User
```

`psd p` returns the error:

```
Error: dup profile for firefox detected. See psd manpage, correct, and try again.
Must have unique last directories in /home/user/.mozilla/firefox/profiles.ini to use psd.
```

Renamed the first one to xxxxxxxx.clean and it correctly appear as managed, the other one not showing up at all.
After removing the space from the second profile (now yyyyyyyy.default) both are picked up and managed by psd.

**Comment by xftroxgpx** [comment]
Firefox Nightly (Mozilla Firefox 60.0a1) creates profile dirs with spaces, eg:
```ini
[General]                                                                       
StartWithLastProfile=0

[Profile0]
Name=Default User
IsRelative=1
Path=8uak94m6.Default User

[Profile1]
Name=Default User@!$'~`
IsRelative=1
Path=fv6w308b.Default User@!$'~`
Default=1

```

They will not be found by current [script](https://github.com/graysky2/profile-sync-daemon/blob/e471c0d666672aad83cd3d65261463a37c3361f3/common/browsers/firefox#L2) due to bash arrays splitting elements by space by default.

**Comment by graysky2** [comment]
Fixed with https://github.com/graysky2/profile-sync-daemon/commit/5f24776e35aae0019c9e9c7fb3ec645fdc5725e4
