### ISSUE TITLE
I require modinfo but it's not installed. Aborting! 

### ISSUE THREAD

**Issue by Moltkex** [graysky2/profile-sync-daemon#253]
Got this error in Buster `I require modinfo but it's not installed. Aborting!` Found this https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1688752.html don't know what to do or how to solve it.

**Comment by graysky2** [comment]
what debian package provided `modinfo`?

**Comment by Moltkex** [comment]
`kmod` provides `modinfo` which is installed.

**Comment by montvid** [comment]
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1688752.html

the bug report says to edit the script to `/sbin/modinfo`. It works afterwards - case closed.

**Comment by Moltkex** [comment]
> https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1688752.html
> 
> the bug report says to edit the script to `/sbin/modinfo`. It works afterwards - case closed.

Can you confirm that it works? I did looked at the script (PSD) but couldn't find where to edit it. Do you have that info?

**Comment by montvid** [comment]
Sorry, 191 line in psd:
`command -v /sbin/modinfo >/dev/null 2>&1 || {`

**Comment by Moltkex** [comment]
> Sorry, 191 line in psd:
> `command -v /sbin/modinfo >/dev/null 2>&1 || {`
> 
> By the way, firefox works visibly faster! Thanks to the authors of this script!

Thank you! That worked! :)

**Comment by graysky2** [comment]
@Moltkex - On Buster, can you please post the output of this command for me:
```
command -pv modinfo
```

**Comment by Moltkex** [comment]
> @Moltkex - On Buster, can you please post the output of this command for me:
> 
> ```
> command -pv modinfo
> ```

It returns nothing. I ran it in a terminal as my regular user and nothing came up, is it that what you asked me to do?. By the way, can't use the overlayfs mode since my kernel doesn't have that. PSD tells to compile a new kernel or something else, can't remember, is there any advantage at using this mode? I know there is but what I mean is, without it, is PSD pointless or nearly pointless?  Where or how can I enable this? Where and how can I get a kernel with this feature? I've never touched a kernel, the furthest I get is install kernels from backports/testing/sid lol  
Thank you.

**Comment by graysky2** [comment]
Something is fucked up with the way Debian sets the PATH, no?

**Comment by Moltkex** [comment]
> Something is fucked up with the way Debian sets the PATH, no?

I think's more like Arch has it's own way of doing things. One of my hobbies is virtualization and out of curiosity tried `command -pv modinfo` in some of my VMs running Fedora, Ubuntu and Slackware and turns out just like in Debian it returns nothing.

**Comment by graysky2** [comment]
I believe the commit above fixes the problem... I don't understand why `/sbin/` isn't included in the PATH whereas `/usr/bin/` or `/bin/` is ...

**Comment by dvzrv** [comment]
@graysky2 it would also be possible to add `/sbin` to `PATH` in your scripts, instead of rerunning the `command -v` call (requires only one line of change and should work on all distros alike).

As a sidenote:
Debian based distros set up their PATH under the assumption, that `/sbin` is supposed to hold "Essential system binaries, e.g., fsck, init, route." (according to [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)) and do not include it in `PATH` by default.
Arch Linux has abolished that idea [when doing the usr-merge in 2013](https://www.archlinux.org/news/binaries-move-to-usrbin-requiring-update-intervention/) (effectively symlinking `/bin`, `/sbin` and `/usr/sbin` to `/usr/bin` and making the latter the default - i.e. bin-merge).
While Debian is working on a [usr-merge](https://wiki.debian.org/UsrMerge) itself, it is not planning a bin-merge (AFAIK).
I guess it is a matter of taste, whether it is a good idea to do a bin-merge or to by default exclude `/sbin` from `PATH` (personally I prefer the former, as it is more simple and the latter doesn't seem to have any real security benefits).
At any rate, I hope nothing to distro-fight over :)

**Comment by graysky2** [comment]
@dvzrv - Thanks for the perspective on this.  I believe the double check I did in that commit will be fine.

**Comment by Moltkex** [comment]
@dvzrv Not to argue or any of the sort but it isn't only Debian and derivatives but as I said in a previous post above, I also noticed that Fedora and Slackware do the same; `command -pv modinfo` returned nothing just like it did in Debian, I confirmed that by running the command in some VMs I have here. What does that mean? not sure. Is it just as you said with Debian? usr-merge approach? I did it cause I was really curious since I installed Buster via netinst.iso so I wanted to know whether or not something was wrong in my system but that wasn't the case. 

@graysky2 Yesterday had a crash, psd had nothing to with it, just happened, the thing's chromium  wouldn't open and I wanted to restore the settings by following the instructions in `man psd` but I couldn't since I use KDE's plasma and it doesn't save chromium settings in ~.config/chromium but in ~.configkde/chromium, I tried by adapting the instructions pointing to that dir but didn't work. I ended up deleting the whole thing. Are there any instructions when it comes to KDE? How do I proceed should this happened again? Thank you.
