### ISSUE TITLE
Encrypted Home support

### ISSUE THREAD

**Issue by TyraelTLK** [graysky2/profile-sync-daemon#34]
Hi, 
how to get profile-sync-daemon working with encrypted home directory?

- add a check for encrypted directory. If it is encrypted and the user is not logged in exit and don't sync (in do_sync() could you check with "ecryptfs-verify -h -u $user" ?)
- start profile-sync-daemon with gnome-session-properties ?
- the user should remember to stop profile-sync-daemon before log out/poweroff

**Comment by pallebone** [comment]
I would also like to ask for this feature. It was working great until I encrypted my home folder, and now I  am forced to live without it.

Pete

**Comment by graysky2** [comment]
I'm not sure how to have the systemd service wait for the user's home dir to be decrypted before attempting the sync without using a user-level hack or user-level systemd service which I've never done before.

**Comment by pallebone** [comment]
This guy did something similar when he had a similar issue. Not sure if its helpful:
http://blog.nozav.org/post/2011/06/30/How-to-use-CrashPlan-with-an-encrypted-home-folder

**Comment by weakish** [comment]
> I'm not sure how to have the systemd service wait for the user's home dir to be decrypted before attempting the sync without using a user-level hack or user-level systemd service

@graysky2  What about using two different config files? The sync script first seeks for config in user's home directory, then in `/etc/`.
Then in `/etc/`, no browsers are listed in the sync list. But in  user's config, the browser they use is listed.
So when psd starts, the sync script does not found user config and sync nothing, since encrypted home is not mounted yet. But on next (or further) sync, the sync scrypt finds the user config, and begin to sync browser profile.

And for unencrypted home users, with this change, they can just change their user config without touching `/etc`. This may be useful if a computer is used by multiple users, and most users cannot `su` or `sudo`.

**Comment by graysky2** [comment]
I don't want to complicate the config situation and since I don't use encryption, I am not very motivated to come up with something.

**Comment by marxjohnson** [comment]
You can work around the issue with an upstart Session Job, which runs `psd sync|unsync` when the desktop session starts and ends, respectively (so post decyption/pre encryption).

Do achieve this, place [this psd.conf file](https://gist.github.com/marxjohnson/ddee2a13f3e0d70a7ea0#file-psd-conf) in ~/.config/upstart/.

Since psd needs to run as root, you'll also need to add the following line to your sudoers (either with visudo or by adding a file to /etc/sudoers.d), while allows your user to run it without a password:
`username ALL=(root) NOPASSWD: /usr/bin/psd`
Replace `username` with your username.  Alternatively, if you have multiple users, add them to a group and replace it with %groupname.

If it's possible to allow psd to run as the normal user rather than as root in this situation, it would make the solution simpler.

When Ubuntu moves to using systemd for sessions, the upstart job will need to be replaced with the systemd equivalent.

**Comment by graysky2** [comment]
I just pushed psd v6.00 which is a step closer to supporting this.  What I don't know is now that is a systemd user service, whether or not systemd will work as-is with the supplied service and with encryption.  I don't have time to setup encryption for testing.  Is anyone here game to try and report back?

1. Does it wait for you to decrypt your $HOME to invoke once it is enabled?
2. Does it run the ExecStop line when you re-encrypt?

**Comment by graysky2** [comment]
Actually, v6.x should now support encrypted /homes.  Please open a new issue if this is not the case.
