### ISSUE TITLE
I must log in as user before starting PSD daemon. (Debian 7.7, iceweasel, NFS+NIS)

### ISSUE THREAD

**Issue by captSpoc** [graysky2/profile-sync-daemon#99]
Hi,
I installed on Debian 7.7, using Iceweasel + NFS home and NIS user.
When it starts, script tells "xxx  is not a valid user. check for typos". If I first log in on gnome session, and then restart PSD, that's ok. When I log out and shutdown the machine, I have yet the same message. The user is not local : may be that's a reason?
It's a bit annoying, since I have to first log without startting my brower, then as root to restart the PSD, and then back to my user session to start the browser.
thanks for your attention

**Comment by graysky2** [comment]
Yes, since your init system starts/stops psd, any user that psd is to manage needs to have his/her $HOME accessible.  In your case, the NFS mount must be getting setup after psd tries and fails to find your $HOME.  This is the same limitation affecting users with encrypted $HOME dirs as well.  With systemd, I think (although did not test to verify), that the included psd.service file will wait for an accessible homedir by virtue of the directive:
`RequiresMountsFor=/home/`

In your case, there might be a way to modify the debian init script I ship with psd to do the same.  I am not a expert with the debian init system and since Debian is eventually going to systemd, am not that motivated to start googling around.  If you are, and if you find a solution via modification of `/etc/init.d/psd` please send me a PR.

**Comment by captSpoc** [comment]
Hi Graysky2,

Thanks for quick reply.
The NFs is mounted : After a reboot, the next day, it does not work anymore. My NFS does not allow local root access (from NFS client). Maybe it is related to that? Is ther a way to have some debug printed somewhere?

Regards

**Comment by graysky2** [comment]
My knowledge of NFS is very basic.  I have setup trivial exports on a NAS before.  What you're talking about is over my head.  I just know that if psd cannot find /home/YOU/PROFILE it will fail.
